"""empty message

Revision ID: a43e3a562606
Revises: 
Create Date: 2026-03-01 11:03:48.503458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43e3a562606'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=True),
    sa.Column('question', sa.String(length=1000), nullable=True),
    sa.Column('choose_a', sa.String(length=100), nullable=True),
    sa.Column('choose_b', sa.String(length=100), nullable=True),
    sa.Column('choose_c', sa.String(length=100), nullable=True),
    sa.Column('choose_d', sa.String(length=100), nullable=True),
    sa.Column('ans', sa.String(length=100), nullable=True),
    sa.Column('total_time', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('test__taken',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=True),
    sa.Column('student', sa.String(length=100), nullable=True),
    sa.Column('score', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=100), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('question', sa.String(length=100), nullable=True),
    sa.Column('relative_score', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test__taken')
    op.drop_table('students')
    op.drop_table('question')
    op.drop_table('admin')
    # ### end Alembic commands ###
